import { X, Sparkles } from 'lucide-react'

export default function PortfolioNoteModal({ open, onClose }) {
  if (!open) return null

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-ink/40 p-4"
      onClick={onClose}
    >
      <div
        role="dialog"
        aria-modal="true"
        aria-labelledby="portfolio-note-title"
        onClick={(e) => e.stopPropagation()}
        className="w-full max-w-md rounded-2xl bg-white p-6 shadow-[0_6px_16px_rgba(11,16,21,0.05),0_1px_2px_rgba(11,16,21,0.04)]"
      >
        <div className="flex items-start justify-between gap-3">
          <div className="flex items-center gap-2">
            <span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-accent-soft">
              <Sparkles size={15} strokeWidth={2} className="text-accent-deep" />
            </span>
            <p id="portfolio-note-title" className="font-display text-[16px] font-semibold text-ink">
              Portfolio case study
            </p>
          </div>
          <button
            type="button"
            onClick={onClose}
            aria-label="Close"
            className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full text-muted hover:bg-surface-inset hover:text-ink"
          >
            <X size={16} />
          </button>
        </div>

        <div className="mt-4 space-y-3 text-[13.5px] leading-snug text-muted">
          <p>
            <span className="font-semibold text-ink">This dashboard is a portfolio case study</span> built
            for Protogen Academy. Maverick, its product catalog, and every metric shown here are
            invented and internally consistent — no real brand, vendor, or customer data is used
            anywhere in this project.
          </p>
          <p>
            The AI-style insight cards, callouts, and recommended actions throughout are
            pre-written to demonstrate how AI-generated guidance could sit alongside real
            merchandising data — they are not generated by a live model against production
            telemetry.
          </p>
          <p>
            Category, size, and return-driver trend figures are an illustrative aggregate layer on
            top of the per-product dataset, built to tell one consistent story rather than
            represent a real system feed.
          </p>
        </div>

        <button
          type="button"
          onClick={onClose}
          className="mt-5 w-full rounded-full bg-ink py-2.5 text-[13.5px] font-semibold text-white hover:bg-ink-soft"
        >
          Got it
        </button>
      </div>
    </div>
  )
}
